[package]
name = "rtc"
version = "0.1.0"
authors = ["mswift42 <martin.haesler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
palette = "0.4.1"
