ws = _{ " " }

comment = _{ ";;" ~ ANY }

comma = _{ "," }

char = { ASCII_ALPHANUMERIC | "_" | "-" }

colorvalue = { "#" ~ ASCII_HEX_DIGIT+ }

fg = { ":foreground" }

bg = { ":background" }

themenamedec = { "(" ~ "deftheme" ~ name ~ ")"}

name = { char+ }

foreground = { ANY+ ~ "default" ~ ANY+ ~ fg ~ colorvar}

background = { ANY+ ~ "default" ~ ANY+ ~ bg ~ colorvar}

faceset = { ANY+ ~ facename ~ ANY+ ~ fg ~ colorvar}

facename = { char+ }


colorvar = { char+ }

