ws = _{ " " }

comment = _{ ";;" ~ ANY }

comma = _{ "," }

char = { ASCII_ALPHANUMERIC | "_" | "-" }

colorvalue = { "#" ~ ASCII_HEX_DIGIT+ }

bg = { ":foreground" }

fg = { ":background" }

themenamedec = { "(" ~ "deftheme" ~ WHITE_SPACE ~ name ~ ")"}

name = { char+ }

foreground = { ANY+ ~ "default" ~ ANY ~ fg ~ WHITE_SPACE ~ colorvar}

background = { ANY+ ~ "default" ~ ANY ~ bg ~ WHITE_SPACE ~ colorvar}

colorvar = { char+ }

