char = { ASCII_ALPHANUMERIC | "." | "_" }

colorvalue = { "#" ~ ASCII_HEX_DIGIT+ }

letdef = {"let"}

variable = {char ~ ":" ~ char+}

vardef = {letdef ~ SPACE_SEPARATOR ~ variable ~ "=" ~ "\""? ~ colorvalue ~ "\""?}

facename = { char+ }

bg = { "guibg" }

fg = { "guifg" }

cterm = { "ctermfg=" | "ctermbg="~ ANY ~ SPACE_SEPARATOR}

facedef = { "exe hi" | "hi"  ~ SPACE_SEPARATOR ~ facename ~ SPACE_SEPARATOR ~ fg | bg }




